server:
  port: 8088
  servlet:
    context-path: /

spring:
    datasource:
        name: springbootTest
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://120.25.146.189:3306/justcall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: justcall123
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    #ES配置
    data:
      elasticsearch:
        cluster-name: justcall-es
        cluster-nodes: 192.168.9.183:9200
        #http://192.168.9.183:9200/
        #http://120.236.21.243:8901/
    #Redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器地址
      host: 120.25.146.189
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: justcall123
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zwb.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:logback-boot.xml
  level:
    com.zwb.mapper: debug



